// GENERATED from the Excellence EHSS Quarterly Performance Review checklist
// (Health & Safety sheet). Codes, texts and weights match the workbook;
// sub-section header typos were normalized (B11, B12, C1).

import type { ChecklistSection } from "./model";

export const CHECKLIST: ChecklistSection[] = [
  { code: "A", title: "Management", subSections: [
    { code: null, title: null, questions: [
      { code: "A1", weight: 4, text: "Is there a strategic plan detailing the program vision, strategic aims, HSSE objectives and targets?" , domain: "cross" },
      { code: "A2", weight: 2, text: "Is there a HSSE execution plan outlining how Contractor Management deliver their roles & responsibilities?" , domain: "cross" },
      { code: "A3", weight: 3, text: "How is Contractor mandatory training (HSSE, Supervisor, CM) conducted and compliance tracked?" , domain: "cross" },
      { code: "A4", weight: 4, text: "Is there specific HSSE audit and inspection schedules? Complied with?" , domain: "cross" },
      { code: "A5", weight: 4, text: "How is HSSE data and reporting managed, monitored & evaluated (including but not limited to Enablon)." , domain: "cross" },
      { code: "A6", weight: 4, text: "Enablon process, management and utilization (users, review and validation process etc.?)" , domain: "cross" },
      { code: "A7", weight: 3, text: "Are incidents investigated - as required by the severity, Incident review panels held and lessons learned shared?" , domain: "cross" },
      { code: "A8", weight: 4, text: "How is HSSE information communicated (alerts, campaigns, LL) and actions tracked where required?" , domain: "cross" },
      { code: "A9", weight: 3, text: "Meeting and communication programs with the contractors, schedule, attendance, comms, tracking actions etc.? (PD/PM HSSE meetings, Safety Forums, Progress and safety meetings)" , domain: "cross" },
      { code: "A10", weight: 2, text: "How does Contractor ensure that HSSE related non-conformities and corrective action are escalated where required? What is the escalation process and responsibilities?" , domain: "cross" },
      { code: "A11", weight: 4, text: "Is there a Reward & Recognition award program and a consequence process?" , domain: "cross" },
      { code: "A12", weight: 4, text: "Show evidence of Monthly HSSE Executive Leadership Meetings, schedule, MoM and action log" , domain: "cross" },
      { code: "A13", weight: 3, text: "Is there a Contractors / Work Order start up / close out process that ensures HSSE requirements are met. Is there a Subcontractor Consent process managed by Contractor? (Readiness Reviews)" , domain: "cross" },
      { code: "A14", weight: 3, text: "Is there a program and process in place for the quarterly Contractor Performance review, including HSSE performance?" , domain: "cross" },
      { code: "A15", weight: 2, text: "How are leadership engagement tours scheduled, measured/recorded and tracked etc.?" , domain: "cross" },
    ] },
  ] },
  { code: "B", title: "Process & Procedures (Assessed on Site)", subSections: [
    { code: "B1", title: "Risk Assessments Method Statements", questions: [
      { code: "B1.1", weight: 3, text: "Are approved risks assessments and method statements (RAMS) available for all current tasks?" , domain: "safety" },
      { code: "B1.2", weight: 3, text: "Are pre start briefings being delivered to employees by supervisors (not H&S) before daily activities start? Records available at point of work and relevant to tasks?" , domain: "safety" },
    ] },
    { code: "B2", title: "Competent Person Designation", questions: [
      { code: "B2.1", weight: 3, text: "Is there adequate supervision and safety cover” (as per the HSAS ratios) at point of work?" , domain: "safety" },
      { code: "B2.2", weight: 2, text: "Is there a process for designation of competent persons on site?" , domain: "safety" },
      { code: "B2.3", weight: 1, text: "Are competent persons identified for hazardous activities?" , domain: "safety" },
      { code: "B2.4", weight: 1, text: "Are the competent persons engaged in the work (at point of work) ?" , domain: "safety" },
    ] },
    { code: "B3", title: "Emergency Response", questions: [
      { code: "B3.1", weight: 3, text: "Does an approved emergency response plan exist?" , domain: "safety" },
      { code: "B3.2", weight: 3, text: "Are employees aware of the plan, and the NEOC emergency numbers (or equivalent) displayed?" , domain: "safety" },
      { code: "B3.3", weight: 3, text: "Is there an approved scenario schedule for drills and are they performed? Are scenarios relative to hazards and risks?" , domain: "safety" },
    ] },
    { code: "B4", title: "Work Permits", questions: [
      { code: "B4.1", weight: 3, text: "Is there a permit to work system? A permit office/process for coordination, issue and closure?" , domain: "safety" },
      { code: "B4.2", weight: 1, text: "Does the permit system require positive verification of the safe condition on completion of works?" , domain: "safety" },
    ] },
    { code: "B5", title: "Utility Clearance", questions: [
      { code: "B5.1", weight: 3, text: "Is there a system for identification of underground utilities?" , domain: "safety" },
      { code: "B5.2", weight: 1, text: "Is the utility clearance system integrated with the work permit system?" , domain: "safety" },
      { code: "B5.3", weight: 1, text: "Does the utility clearance system apply to all ground and structure penetration activities?" , domain: "safety" },
    ] },
    { code: "B6", title: "Subcontractor Management", questions: [
      { code: "B6.1", weight: 3, text: "Does the contractor have a subcontractor screening and evaluation process, is this monitored?" , domain: "cross" },
      { code: "B6.2", weight: 2, text: "Was an assessment carried out for HSSE Compliance for each subcontractor engaged on the project prior to commencing work on site?" , domain: "cross" },
      { code: "B6.3", weight: 2, text: "Was documented criteria used to evaluate the subcontractors past HSE performance and existing or proposed systems?" , domain: "cross" },
      { code: "B6.4", weight: 1, text: "Have supervision arrangements for each subcontractor been confirmed and documented?" , domain: "cross" },
      { code: "B6.5", weight: 1, text: "How is each subcontractors HSSE performance tracked and reported throughout the project lifecycle?" , domain: "cross" },
      { code: "B6.6", weight: 1, text: "Have actions been taken to improve subcontractor HSSE performance that does not meet expectations and have those actions been effective?" , domain: "cross" },
      { code: "B6.7", weight: 2, text: "Are the electrician and electrical supervisors assessed for the competency and Are the inspections carried out by the electrical supervisor or Engineer on the electrical installations?" , domain: "cross" },
      { code: "B6.8", weight: 2, text: "Is there an up-to-date register of electrical equipment?" , domain: "cross" },
      { code: "B6.9", weight: 1, text: "Does the contractor hold regular safety meetings with subcontractors?" , domain: "cross" },
    ] },
    { code: "B7", title: "Training", questions: [
      { code: "B7.1", weight: 2, text: "HSE Training requirements have been identified, implemented and recorded." , domain: "cross" },
      { code: "B7.2", weight: 1, text: "Has a NEOM approved HSE Induction has been delivered to all employees and visitors? Term before re-fresher required identified and how managed?" , domain: "cross" },
    ] },
    { code: "B8", title: "Incident Reporting", questions: [
      { code: "B8.1", weight: 4, text: "Are employees aware of a process for reporting incidents and observations? Posters/Charts displayed?" , domain: "cross" },
    ] },
    { code: "B9", title: "Fire Prevention", questions: [
      { code: "B9.1", weight: 1, text: "Are fire extinguishers and fire fighting equipment properly located inspected and maintained?" , domain: "safety" },
      { code: "B9.2", weight: 1, text: "Are Oxy-fuel rigs properly set up and stored and flashback arrestors are properly installed?" , domain: "safety" },
      { code: "B9.3", weight: 1, text: "Are flammables, oxidizers, and combustibles stored properly?" , domain: "safety" },
    ] },
    { code: "B10", title: "Personal Protective Equipment", questions: [
      { code: "B10.1", weight: 3, text: "Is there a PPE policy (including NEOM 5 point PPE) is it implemented and managed?" , domain: "safety" },
      { code: "B10.2", weight: 1, text: "Is task specific PPE provided where required (i.e. SCBA for confined space work etc.)" , domain: "safety" },
    ] },
    { code: "B11", title: "Medical", questions: [
      { code: "B11.1", weight: 3, text: "Is there a suitable medical facilities and ambulance available?" , domain: "health" },
      { code: "B11.2", weight: 2, text: "Are there enough qualified medical staff (doctor, nurse, paramedics) on site?" , domain: "health" },
      { code: "B11.3", weight: 2, text: "Are there enough first aid trained employees on site, how are the identified?" , domain: "health" },
    ] },
    { code: "B12", title: "Occupational and Health Surveillance", questions: [
      { code: "B12.1", weight: 3, text: "Is there an occupational and health program/plan implemented and recorded?" , domain: "health" },
      { code: "B12.2", weight: 1, text: "Is there a health surveillance program?" , domain: "health" },
    ] },
  ] },
  { code: "C", title: "Planning & Commitment", subSections: [
    { code: "C1", title: "Leadership Engagement", questions: [
      { code: "C1.1", weight: 2, text: "Do you have an established Health & Safety Steering Committee, and is senior management represented on it?" , domain: "cross" },
      { code: "C1.2", weight: 2, text: "What actions were made by the Sr management during the walkthrough" , domain: "cross" },
      { code: "C1.3", weight: 1, text: "Are there minutes available for the most recent HSE SC, Has the following been reviewed and discussed, Injuries, illnesses, HIPO Nearmisses, HIPO Unsafe behaviours and conditions?" , domain: "cross" },
      { code: "C1.4", weight: 1, text: "Do you have a schedule for the Audit and Is there an evidence of recent audit report and is it reviewed by the Sr management (E.G Steering committee)?" , domain: "cross" },
      { code: "C1.5", weight: 1, text: "Do you have a schedule for Senior Management (PD & CEO), and does it include their participation in Health & Safety walkthroughs" , domain: "cross" },
      { code: "C1.6", weight: 3, text: "What NC's / Opportunity For Improvements and recomendations for Corrective Action's were made by the auditor?" , domain: "cross" },
      { code: "C1.7", weight: 1, text: "Do you have a schedule for the Mass TBT and Does the schedule includes participation by the Sr management (External PD & CEO)" , domain: "cross" },
      { code: "C1.8", weight: 1, text: "Is there evidence of recognition and rewarding for frontline workforce reporting of high potential nearmisses and observations relating to critical controls (signficant Hazards)?" , domain: "cross" },
      { code: "C1.9", weight: 2, text: "Do managers and supervisors ensure that Risk Assessments and Method Statements (RAMS) are approved, communicated, and implemented for all work activities?" , domain: "safety" },
      { code: "C1.10", weight: 1, text: "Are RAMS available for all activities (check the RAMS register)? Take sample of activities on site, a copy of the RAMS must be available on site." , domain: "safety" },
      { code: "C1.11", weight: 3, text: "Do the requirements specified in the RAMS accurately reflect the work activity being conducted? (Specific activity covered, all relevant significant hazards identified, all mandated controls in place)" , domain: "safety" },
      { code: "C1.12", weight: 1, text: "Is there a documented review process for RAMS and does it include authorization by the relevant Construction Manager / Employer?" , domain: "safety" },
    ] },
    { code: "C2", title: "Planning", questions: [
      { code: "C2.2", weight: 2, text: "Is there upto date and Code A Employer (Oxagon Projects) approved HSSE plan ?" , domain: "cross" },
      { code: "C2.3", weight: 1, text: "Is there upto date and Employer (Oxagon Projects) approved HSSE Monitoring Schedule?" , domain: "cross" },
      { code: "C2.4", weight: 1, text: "Is there upto date and Employer (Oxagon Projects) approved Training Matrix, Records and Plan and Is there upto date and Employer (Oxagon Projects) approved Induction Presentation?" , domain: "cross" },
      { code: "C2.5", weight: 1, text: "Is there upto date and Employer (Oxagon Projects) approved HSSE Personnel CV's?" , domain: "cross" },
      { code: "C2.6", weight: 1, text: "Is there Employer approved HSSE Reward and Recognition Scheme?" , domain: "cross" },
      { code: "C2.7", weight: 1, text: "Is there upto date and Employer (Oxagon Projects) approved Emergency Management and Emergency Response Plan?" , domain: "safety" },
      { code: "C2.8", weight: 2, text: "Is there upto date and Employer (Oxagon Projects) approved Injury / Illness Management Plan?" , domain: "health" },
      { code: "C2.9", weight: 1, text: "Is there upto date and Employer (Oxagon Projects) approved Subcontractor Management Plan?" , domain: "cross" },
      { code: "C2.10", weight: 1, text: "Is there upto date and Employer (Oxagon Projects) approved Traffic Management and Logistics Plan?" , domain: "safety" },
      { code: "C2.11", weight: 1, text: "Is there upto date and Employer (Oxagon Projects) approved Lifting Operations Management Plan and Lift Plan?" , domain: "safety" },
      { code: "C2.12", weight: 2, text: "Is there upto date and Employer (Oxagon Projects) approved Fatigue Management Plan?" , domain: "health" },
      { code: "C2.13", weight: 1, text: "Is there upto date and Employer (Oxagon Projects) approved Fire Prevention Plan?" , domain: "safety" },
      { code: "C2.14", weight: 1, text: "Is there upto date and Employer (Oxagon Projects) approved Temporary Electrical Management Safety Plan?" , domain: "safety" },
      { code: "C2.15", weight: 1, text: "Is there upto date and Employer (Oxagon Projects) approved Testing Commissioning Plans?" , domain: "safety" },
      { code: "C2.16", weight: 1, text: "Is there upto date and Employer (Oxagon Projects) approved Temporary Works Procedure / Register / Management Plan?" , domain: "safety" },
      { code: "C2.17", weight: 3, text: "Is there upto date and Employer (Oxagon Projects) approved Weather working Plan?" , domain: "health" },
      { code: "C2.18", weight: 3, text: "Is there upto date and Employer (Oxagon Projects) approved Equipment Inspection Program" , domain: "safety" },
      { code: "C2.19", weight: 1, text: "Is there upto date and Employer (Oxagon Projects) approved Mobilization & Demobilization Plan" , domain: "cross" },
    ] },
  ] },
];

/** The workbook's own filled audit, used as a scoring test fixture. */
export const WORKBOOK_FIXTURE_ANSWERS: Record<string, "full" | "partial" | "no" | "na"> = {
  "A1": "partial",
  "A2": "no",
  "A3": "partial",
  "A4": "partial",
  "A5": "partial",
  "A6": "partial",
  "A7": "partial",
  "A8": "full",
  "A9": "partial",
  "A10": "full",
  "A11": "partial",
  "A12": "no",
  "A13": "partial",
  "A14": "no",
  "A15": "partial",
  "B1.1": "full",
  "B1.2": "full",
  "B2.1": "full",
  "B2.2": "full",
  "B2.3": "partial",
  "B2.4": "full",
  "B3.1": "full",
  "B3.2": "full",
  "B3.3": "partial",
  "B4.1": "partial",
  "B4.2": "partial",
  "B5.1": "full",
  "B5.2": "full",
  "B5.3": "full",
  "B6.1": "partial",
  "B6.2": "partial",
  "B6.3": "no",
  "B6.4": "no",
  "B6.5": "no",
  "B6.6": "partial",
  "B6.7": "partial",
  "B6.8": "partial",
  "B6.9": "no",
  "B7.1": "partial",
  "B7.2": "partial",
  "B8.1": "partial",
  "B9.1": "full",
  "B9.2": "na",
  "B9.3": "full",
  "B10.1": "full",
  "B10.2": "full",
  "B11.1": "full",
  "B11.2": "partial",
  "B11.3": "full",
  "B12.1": "partial",
  "B12.2": "partial",
  "C1.1": "na",
  "C1.2": "partial",
  "C1.3": "na",
  "C1.4": "na",
  "C1.5": "na",
  "C1.6": "na",
  "C1.7": "na",
  "C1.8": "full",
  "C1.9": "partial",
  "C1.10": "na",
  "C1.11": "partial",
  "C1.12": "no",
  "C2.2": "full",
  "C2.3": "partial",
  "C2.4": "full",
  "C2.5": "full",
  "C2.6": "partial",
  "C2.7": "full",
  "C2.8": "full",
  "C2.9": "partial",
  "C2.10": "partial",
  "C2.11": "full",
  "C2.12": "full",
  "C2.13": "full",
  "C2.14": "partial",
  "C2.15": "no",
  "C2.16": "full",
  "C2.17": "partial",
  "C2.18": "partial",
  "C2.19": "partial",
};
