/**
 * GENERATED — do not edit by hand.
 *   python3 scripts/build-recorded-dataset.py \
 *       data/hs-audits-2025Q4-2026Q1.json > src/lib/ehss/recorded.ts
 *
 * The real Health & Safety audits for Q4 2025 and Q1 2026, as read from
 * HS_AUDIT_FINDINGS.xlsx. This is the app's dataset: there is no demo data.
 *
 * Contractors are INITIALS + THE LAST THREE DIGITS OF THE WORK ORDER, which
 * is all the app ever sees. It keeps the dataset unidentifying, and it
 * settles the source file's three spellings of SIBS by construction.
 *
 * Each audit carries the checklist's 15 AREA scores as raw points, not
 * per-question answers: the sheet records a narrative per question and no
 * machine-readable answer, so there is nothing honest to put in `responses`.
 * `possible` varies between audits because N/A questions drop out of it,
 * which is the workbook's own rule.
 *
 * `reportedTotal` is the total the sheet stated. It disagrees with the
 * sheet's own points in 7 of 20 audits (see docs/IMPORT-2025Q4-2026Q1.md);
 * the app scores the points and shows the stated figure beside it rather
 * than quietly picking one.
 */

import type { EhssAudit, EhssContractor, SubRegion } from "./model";

export const subRegions: SubRegion[] = [
  { id: "sr1", name: "Sub Region 1" },
  { id: "sr2", name: "Sub Region 2" },
];

export const contractors: EhssContractor[] = [
  { id: "ab901", code: "901", name: "AB", subRegionId: "sr1", active: true },
  { id: "abya112", code: "112", name: "ABYA", subRegionId: "sr1", active: true },
  { id: "abya134", code: "134", name: "ABYA", subRegionId: "sr1", active: true },
  { id: "af882", code: "882", name: "AF", subRegionId: "sr1", active: true },
  { id: "nbc026", code: "026", name: "NBC", subRegionId: "sr1", active: true },
  { id: "ppco322", code: "322", name: "PPCO", subRegionId: "sr1", active: true },
  { id: "rpco440", code: "440", name: "RPCO", subRegionId: "sr1", active: true },
  { id: "sibs838", code: "838", name: "SIBS", subRegionId: "sr1", active: true },
  { id: "tdp892", code: "892", name: "TDP", subRegionId: "sr1", active: true },
  { id: "af272", code: "272", name: "AF", subRegionId: "sr2", active: true },
  { id: "ech131", code: "131", name: "ECH", subRegionId: "sr2", active: true },
  { id: "ot2db", code: "D&B", name: "OT2", subRegionId: "sr2", active: true },
  { id: "sd876", code: "876", name: "SD", subRegionId: "sr2", active: true },
];

export const audits: EhssAudit[] = [
  {
    id: "ab901-2025-Q4",
    contractorId: "ab901",
    quarter: "2025-Q4",
    auditDate: "2025-10-20",
    inspectionNo: "HSW-01",
    status: "approved",
    responses: {},
    disciplineScores: {},
    criticalRisks: {},
    reportedTotal: 68,
    areaScores: {
      A: { scored: 36, possible: 45 },
      B1: { scored: 3, possible: 6 },
      B2: { scored: 4, possible: 6 },
      B3: { scored: 4.5, possible: 9 },
      B4: { scored: 2, possible: 4 },
      B6: { scored: 2, possible: 15 },
      B7: { scored: 1.5, possible: 3 },
      B8: { scored: 1.5, possible: 3 },
      B9: { scored: 0.5, possible: 1 },
      B10: { scored: 1.5, possible: 3 },
      B11: { scored: 6, possible: 7 },
      B12: { scored: 4, possible: 4 },
      C1: { scored: 8, possible: 13 },
      C2: { scored: 21, possible: 21 },
    },
  },
  {
    id: "abya112-2025-Q4",
    contractorId: "abya112",
    quarter: "2025-Q4",
    auditDate: "2025-10-15",
    inspectionNo: "HSW-01",
    status: "approved",
    responses: {},
    disciplineScores: {},
    criticalRisks: {},
    reportedTotal: 62.09,
    areaScores: {
      A: { scored: 25.5, possible: 45 },
      B1: { scored: 4.5, possible: 6 },
      B2: { scored: 6, possible: 7 },
      B3: { scored: 6, possible: 9 },
      B4: { scored: 2, possible: 4 },
      B6: { scored: 11, possible: 15 },
      B7: { scored: 1.5, possible: 3 },
      B8: { scored: 1.5, possible: 3 },
      B9: { scored: 1.5, possible: 3 },
      B10: { scored: 2, possible: 4 },
      B11: { scored: 6, possible: 7 },
      B12: { scored: 2, possible: 4 },
      C1: { scored: 7, possible: 13 },
      C2: { scored: 17.5, possible: 21 },
    },
  },
  {
    id: "abya134-2025-Q4",
    contractorId: "abya134",
    quarter: "2025-Q4",
    auditDate: "2025-10-22",
    inspectionNo: "HSW-01",
    status: "approved",
    responses: {},
    disciplineScores: {},
    criticalRisks: {},
    reportedTotal: 67,
    areaScores: {
      A: { scored: 27, possible: 45 },
      B1: { scored: 6, possible: 6 },
      B2: { scored: 6, possible: 7 },
      B3: { scored: 6, possible: 9 },
      B4: { scored: 2, possible: 4 },
      B5: { scored: 5, possible: 5 },
      B6: { scored: 3, possible: 15 },
      B7: { scored: 1.5, possible: 3 },
      B8: { scored: 1.5, possible: 3 },
      B9: { scored: 0.5, possible: 1 },
      B10: { scored: 1.5, possible: 3 },
      B11: { scored: 5, possible: 7 },
      B12: { scored: 2, possible: 4 },
      C1: { scored: 4.5, possible: 13 },
      C2: { scored: 15, possible: 21 },
    },
  },
  {
    id: "af272-2025-Q4",
    contractorId: "af272",
    quarter: "2025-Q4",
    auditDate: "2025-10-29",
    inspectionNo: "HSW-01",
    status: "approved",
    responses: {},
    disciplineScores: {},
    criticalRisks: {},
    reportedTotal: 71,
    areaScores: {
      A: { scored: 30, possible: 45 },
      B1: { scored: 4.5, possible: 6 },
      B2: { scored: 6.5, possible: 7 },
      B3: { scored: 7.5, possible: 9 },
      B4: { scored: 2, possible: 4 },
      B5: { scored: 5, possible: 5 },
      B6: { scored: 6.5, possible: 15 },
      B7: { scored: 1.5, possible: 3 },
      B8: { scored: 3, possible: 3 },
      B9: { scored: 2, possible: 2 },
      B10: { scored: 2.5, possible: 4 },
      B11: { scored: 7, possible: 7 },
      B12: { scored: 3.5, possible: 4 },
      C1: { scored: 9, possible: 13 },
      C2: { scored: 19, possible: 21 },
    },
  },
  {
    id: "ech131-2025-Q4",
    contractorId: "ech131",
    quarter: "2025-Q4",
    auditDate: "2025-11-03",
    inspectionNo: "HSW-01",
    status: "approved",
    responses: {},
    disciplineScores: {},
    criticalRisks: {},
    reportedTotal: 74,
    areaScores: {
      A: { scored: 33, possible: 45 },
      B1: { scored: 4.5, possible: 6 },
      B2: { scored: 6, possible: 7 },
      B3: { scored: 9, possible: 9 },
      B4: { scored: 2, possible: 4 },
      B5: { scored: 5, possible: 5 },
      B6: { scored: 5.5, possible: 15 },
      B7: { scored: 2.5, possible: 3 },
      B8: { scored: 3, possible: 3 },
      B9: { scored: 1.5, possible: 2 },
      B10: { scored: 2.5, possible: 4 },
      B11: { scored: 7, possible: 7 },
      B12: { scored: 2, possible: 4 },
      C1: { scored: 11, possible: 13 },
      C2: { scored: 16.5, possible: 21 },
    },
  },
  {
    id: "ot2db-2025-Q4",
    contractorId: "ot2db",
    quarter: "2025-Q4",
    auditDate: "2025-12-01",
    inspectionNo: "HS-01",
    status: "approved",
    responses: {},
    disciplineScores: {},
    criticalRisks: {},
    reportedTotal: 64,
    areaScores: {
      A: { scored: 27, possible: 42 },
      B1: { scored: 3, possible: 6 },
      B2: { scored: 4, possible: 7 },
      B3: { scored: 4.5, possible: 9 },
      B4: { scored: 2, possible: 4 },
      B5: { scored: 5, possible: 5 },
      B6: { scored: 1, possible: 11 },
      B7: { scored: 1.5, possible: 3 },
      B8: { scored: 1.5, possible: 3 },
      B9: { scored: 2.5, possible: 3 },
      B10: { scored: 2.5, possible: 4 },
      B11: { scored: 6, possible: 7 },
      B12: { scored: 2, possible: 4 },
      C1: { scored: 9, possible: 13 },
      C2: { scored: 18, possible: 21 },
    },
  },
  {
    id: "ppco322-2025-Q4",
    contractorId: "ppco322",
    quarter: "2025-Q4",
    auditDate: "2025-10-13",
    inspectionNo: "HSW-01",
    status: "approved",
    responses: {},
    disciplineScores: {},
    criticalRisks: {},
    reportedTotal: 62,
    areaScores: {
      A: { scored: 21, possible: 42 },
      B1: { scored: 1.5, possible: 3 },
      B2: { scored: 5.5, possible: 6 },
      B3: { scored: 4.5, possible: 9 },
      B4: { scored: 2, possible: 4 },
      B5: { scored: 4, possible: 4 },
      B6: { scored: 0, possible: 11 },
      B7: { scored: 1.5, possible: 3 },
      B8: { scored: 3, possible: 3 },
      B9: { scored: 2, possible: 3 },
      B10: { scored: 4, possible: 4 },
      B11: { scored: 7, possible: 7 },
      B12: { scored: 2.5, possible: 4 },
      C1: { scored: 8, possible: 13 },
      C2: { scored: 20.5, possible: 21 },
    },
  },
  {
    id: "sibs838-2025-Q4",
    contractorId: "sibs838",
    quarter: "2025-Q4",
    auditDate: "2025-11-19",
    inspectionNo: "HSW-01",
    status: "approved",
    responses: {},
    disciplineScores: {},
    criticalRisks: {},
    reportedTotal: 65,
    areaScores: {
      A: { scored: 30, possible: 45 },
      B1: { scored: 6, possible: 6 },
      B2: { scored: 7, possible: 7 },
      B3: { scored: 7.5, possible: 9 },
      B4: { scored: 2.5, possible: 4 },
      B6: { scored: 5, possible: 15 },
      B7: { scored: 1.5, possible: 3 },
      B8: { scored: 3, possible: 3 },
      B9: { scored: 2, possible: 2 },
      B10: { scored: 2.5, possible: 4 },
      B11: { scored: 6, possible: 7 },
      B12: { scored: 2, possible: 4 },
      C1: { scored: 8.5, possible: 13 },
      C2: { scored: 12.5, possible: 21 },
    },
  },
  {
    id: "abya112-2026-Q1",
    contractorId: "abya112",
    quarter: "2026-Q1",
    auditDate: "2026-03-08",
    inspectionNo: "HSSEW-002",
    status: "approved",
    responses: {},
    disciplineScores: {},
    criticalRisks: {},
    reportedTotal: 60,
    areaScores: {
      A: { scored: 19.5, possible: 36 },
      B1: { scored: 6, possible: 6 },
      B2: { scored: 5, possible: 7 },
      B3: { scored: 7.5, possible: 9 },
      B4: { scored: 2, possible: 4 },
      B6: { scored: 6, possible: 15 },
      B7: { scored: 1.5, possible: 3 },
      B8: { scored: 1.5, possible: 3 },
      B9: { scored: 1.5, possible: 2 },
      B10: { scored: 3, possible: 3 },
      B11: { scored: 5, possible: 7 },
      B12: { scored: 2, possible: 4 },
      C1: { scored: 2.5, possible: 13 },
      C2: { scored: 14, possible: 21 },
    },
  },
  {
    id: "abya134-2026-Q1",
    contractorId: "abya134",
    quarter: "2026-Q1",
    auditDate: "2026-03-10",
    inspectionNo: "HSSEW-002",
    status: "approved",
    responses: {},
    disciplineScores: {},
    criticalRisks: {},
    reportedTotal: 64,
    areaScores: {
      A: { scored: 21, possible: 36 },
      B1: { scored: 6, possible: 6 },
      B2: { scored: 6.5, possible: 7 },
      B3: { scored: 6, possible: 9 },
      B4: { scored: 3.5, possible: 4 },
      B5: { scored: 4, possible: 4 },
      B6: { scored: 4.5, possible: 15 },
      B7: { scored: 2, possible: 3 },
      B8: { scored: 1.5, possible: 3 },
      B9: { scored: 2, possible: 2 },
      B10: { scored: 4, possible: 4 },
      B11: { scored: 6, possible: 7 },
      B12: { scored: 2, possible: 4 },
      C1: { scored: 3.5, possible: 13 },
      C2: { scored: 13, possible: 21 },
    },
  },
  {
    id: "af272-2026-Q1",
    contractorId: "af272",
    quarter: "2026-Q1",
    auditDate: "2026-02-23",
    inspectionNo: "HSSEW-002",
    status: "approved",
    responses: {},
    disciplineScores: {},
    criticalRisks: {},
    reportedTotal: 65,
    areaScores: {
      A: { scored: 20, possible: 40 },
      B1: { scored: 6, possible: 6 },
      B2: { scored: 6.5, possible: 7 },
      B3: { scored: 9, possible: 9 },
      B4: { scored: 2.5, possible: 4 },
      B5: { scored: 5, possible: 5 },
      B6: { scored: 3, possible: 15 },
      B7: { scored: 2, possible: 3 },
      B8: { scored: 2, possible: 4 },
      B9: { scored: 2, possible: 2 },
      B10: { scored: 4, possible: 4 },
      B11: { scored: 6, possible: 7 },
      B12: { scored: 1.5, possible: 4 },
      C1: { scored: 5, possible: 19 },
      C2: { scored: 18, possible: 21 },
    },
  },
  {
    id: "af882-2026-Q1",
    contractorId: "af882",
    quarter: "2026-Q1",
    auditDate: "2026-01-25",
    inspectionNo: "HSSEW-002",
    status: "approved",
    responses: {},
    disciplineScores: {},
    criticalRisks: {},
    reportedTotal: 68,
    areaScores: {
      A: { scored: 27, possible: 45 },
      B1: { scored: 6, possible: 6 },
      B2: { scored: 6, possible: 7 },
      B3: { scored: 7.5, possible: 9 },
      B4: { scored: 2.5, possible: 4 },
      B5: { scored: 5, possible: 5 },
      B6: { scored: 6.5, possible: 15 },
      B7: { scored: 1.5, possible: 3 },
      B8: { scored: 1.5, possible: 3 },
      B9: { scored: 2, possible: 2 },
      B10: { scored: 3, possible: 3 },
      B11: { scored: 4, possible: 7 },
      B12: { scored: 2, possible: 4 },
      C1: { scored: 8.5, possible: 13 },
      C2: { scored: 20, possible: 21 },
    },
  },
  {
    id: "ech131-2026-Q1",
    contractorId: "ech131",
    quarter: "2026-Q1",
    auditDate: "2026-03-01",
    inspectionNo: "HSSEW-002",
    status: "approved",
    responses: {},
    disciplineScores: {},
    criticalRisks: {},
    reportedTotal: 85,
    areaScores: {
      A: { scored: 25.5, possible: 36 },
      B1: { scored: 6, possible: 6 },
      B2: { scored: 5.5, possible: 7 },
      B3: { scored: 9, possible: 9 },
      B4: { scored: 2.5, possible: 4 },
      B5: { scored: 5, possible: 5 },
      B6: { scored: 9.5, possible: 15 },
      B7: { scored: 2, possible: 3 },
      B8: { scored: 1.5, possible: 3 },
      B9: { scored: 2, possible: 2 },
      B10: { scored: 4, possible: 4 },
      B11: { scored: 5, possible: 7 },
      B12: { scored: 1.5, possible: 4 },
      C1: { scored: 6.5, possible: 13 },
      C2: { scored: 21, possible: 21 },
    },
  },
  {
    id: "nbc026-2026-Q1",
    contractorId: "nbc026",
    quarter: "2026-Q1",
    auditDate: "2026-02-08",
    inspectionNo: "HSSEW-002",
    status: "approved",
    responses: {},
    disciplineScores: {},
    criticalRisks: {},
    reportedTotal: 60,
    areaScores: {
      A: { scored: 13.5, possible: 42 },
      B1: { scored: 4.5, possible: 6 },
      B2: { scored: 4.5, possible: 7 },
      B3: { scored: 6, possible: 9 },
      B4: { scored: 2, possible: 4 },
      B5: { scored: 5, possible: 5 },
      B6: { scored: 2, possible: 11 },
      B7: { scored: 1.5, possible: 3 },
      B8: { scored: 3, possible: 3 },
      B9: { scored: 1.5, possible: 2 },
      B10: { scored: 1.5, possible: 3 },
      B11: { scored: 7, possible: 7 },
      B12: { scored: 2.5, possible: 4 },
      C1: { scored: 6, possible: 13 },
      C2: { scored: 12.5, possible: 21 },
    },
  },
  {
    id: "ppco322-2026-Q1",
    contractorId: "ppco322",
    quarter: "2026-Q1",
    auditDate: "2026-01-18",
    inspectionNo: "HSSEW-002",
    status: "approved",
    responses: {},
    disciplineScores: {},
    criticalRisks: {},
    reportedTotal: 76,
    areaScores: {
      A: { scored: 30, possible: 45 },
      B1: { scored: 4.5, possible: 6 },
      B2: { scored: 6, possible: 7 },
      B3: { scored: 6, possible: 9 },
      B4: { scored: 2.5, possible: 4 },
      B5: { scored: 5, possible: 5 },
      B6: { scored: 0, possible: 11 },
      B7: { scored: 2, possible: 3 },
      B8: { scored: 3, possible: 3 },
      B9: { scored: 2, possible: 3 },
      B10: { scored: 3, possible: 3 },
      B11: { scored: 6, possible: 7 },
      B12: { scored: 3.5, possible: 4 },
      C1: { scored: 8, possible: 13 },
      C2: { scored: 17, possible: 21 },
    },
  },
  {
    id: "rpco440-2026-Q1",
    contractorId: "rpco440",
    quarter: "2026-Q1",
    auditDate: "2026-03-02",
    inspectionNo: "HSSEW-002",
    status: "approved",
    responses: {},
    disciplineScores: {},
    criticalRisks: {},
    reportedTotal: 60,
    areaScores: {
      A: { scored: 7.5, possible: 39 },
      B1: { scored: 3, possible: 6 },
      B2: { scored: 6, possible: 7 },
      B3: { scored: 7.5, possible: 9 },
      B4: { scored: 2, possible: 4 },
      B5: { scored: 5, possible: 5 },
      B6: { scored: 1, possible: 11 },
      B7: { scored: 1.5, possible: 3 },
      B8: { scored: 3, possible: 3 },
      B9: { scored: 2, possible: 2 },
      B10: { scored: 3, possible: 3 },
      B11: { scored: 6, possible: 7 },
      B12: { scored: 2, possible: 4 },
      C1: { scored: 3, possible: 13 },
      C2: { scored: 14.5, possible: 21 },
    },
  },
  {
    id: "sd876-2026-Q1",
    contractorId: "sd876",
    quarter: "2026-Q1",
    auditDate: "2026-02-15",
    inspectionNo: "HSSEW-002",
    status: "approved",
    responses: {},
    disciplineScores: {},
    criticalRisks: {},
    reportedTotal: 66,
    areaScores: {
      A: { scored: 21, possible: 42 },
      B1: { scored: 4.5, possible: 6 },
      B2: { scored: 5, possible: 7 },
      B3: { scored: 9, possible: 9 },
      B4: { scored: 3.5, possible: 4 },
      B5: { scored: 5, possible: 5 },
      B6: { scored: 3, possible: 15 },
      B7: { scored: 2, possible: 3 },
      B8: { scored: 1.5, possible: 3 },
      B9: { scored: 3, possible: 3 },
      B10: { scored: 4, possible: 4 },
      B11: { scored: 7, possible: 7 },
      B12: { scored: 1.5, possible: 4 },
      C1: { scored: 3, possible: 13 },
      C2: { scored: 19, possible: 21 },
    },
  },
  {
    id: "sibs838-2026-Q1",
    contractorId: "sibs838",
    quarter: "2026-Q1",
    auditDate: "2026-02-01",
    inspectionNo: "HSSEW-002",
    status: "approved",
    responses: {},
    disciplineScores: {},
    criticalRisks: {},
    reportedTotal: 72,
    areaScores: {
      A: { scored: 30, possible: 45 },
      B1: { scored: 6, possible: 6 },
      B2: { scored: 7, possible: 7 },
      B3: { scored: 7.5, possible: 9 },
      B4: { scored: 2, possible: 4 },
      B6: { scored: 7, possible: 15 },
      B7: { scored: 1.5, possible: 3 },
      B8: { scored: 3, possible: 3 },
      B9: { scored: 2, possible: 2 },
      B10: { scored: 4, possible: 4 },
      B11: { scored: 6, possible: 7 },
      B12: { scored: 3.5, possible: 4 },
      C1: { scored: 9, possible: 13 },
      C2: { scored: 15.5, possible: 21 },
    },
  },
  {
    id: "tdp892-2026-Q1",
    contractorId: "tdp892",
    quarter: "2026-Q1",
    auditDate: "2026-03-15",
    inspectionNo: "HSSEW-002",
    status: "approved",
    responses: {},
    disciplineScores: {},
    criticalRisks: {},
    reportedTotal: 62,
    areaScores: {
      A: { scored: 18, possible: 36 },
      B1: { scored: 6, possible: 6 },
      B2: { scored: 6, possible: 6 },
      B3: { scored: 7.5, possible: 9 },
      B4: { scored: 2, possible: 4 },
      B6: { scored: 1, possible: 11 },
      B7: { scored: 1.5, possible: 3 },
      B8: { scored: 1.5, possible: 3 },
      B9: { scored: 1, possible: 1 },
      B10: { scored: 3, possible: 3 },
      B11: { scored: 6, possible: 7 },
      B12: { scored: 2, possible: 4 },
      C1: { scored: 8.5, possible: 13 },
      C2: { scored: 15.5, possible: 21 },
    },
  },
];

export const contractorById = new Map(contractors.map((c) => [c.id, c]));
export const subRegionById = new Map(subRegions.map((s) => [s.id, s]));
